version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      JDBC_URL: jdbc:postgresql://db:5432/notification
      JDBC_USER: admin
      JDBC_PASSWORD: admin
    ports:
      - 8080:8080
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: notification
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql