micronaut:
  application:
    name: notification

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    useBigIntegerForInts: true
    failOnUnknownProperties: false

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/notification`}
    driverClassName: org.postgresql.Driver
    username: ${JDBC_USER:admin}
    password: ${JDBC_PASSWORD:admin}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
