micronaut:
  application:
    name: notification

jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    useBigIntegerForInts: true
    failOnUnknownProperties: false

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/notification
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
